"""
Walk-forward backtesting framework for the XGBoost forecasting model.
 
Walk-forward methodology
------------------------
Unlike a simple train/test split, walk-forward testing retrains the model
periodically as new data arrives. This more realistically simulates production
deployment, where the model would be retrained on a schedule.
 
Procedure
---------
1. Train an initial XGBoost model on the training split.
2. Iterate over the test set one row at a time.
3. Every `retrain_interval` rows, retrain on all data seen so far (expanding window).
4. Append predictions and collect final evaluation metrics.
 
This produces a single set of predictions that were each generated by a model
that had only seen data prior to that prediction — no look-ahead.
"""





import pandas as pd
import numpy as np
from config.settings import FEATURES, TARGET_COL, TRAIN_SPLIT
from src.forecasting import train_xgboost, evaluate



# Perform a walk-forward backtest with periodic model retraining.

def walk_forward_backtest(
    df: pd.DataFrame,
    retrain_interval: int = 50,
) -> tuple:
    n     = int(len(df) * TRAIN_SPLIT)
    train = df.iloc[:n].copy()
    test  = df.iloc[n:].copy()

    model   = train_xgboost(train[FEATURES], train["return"])
    history = train.copy()
    preds   = []

    for i in range(len(test)):
        if i % retrain_interval == 0 and len(history) > retrain_interval:
            model = train_xgboost(history[FEATURES], history["return"])
        preds.append(float(model.predict(test[FEATURES].iloc[i:i+1])[0]))
        history = pd.concat([history, test.iloc[i:i+1]])

    metrics = evaluate(test["return"].values, preds, label="Walk-forward")
    return preds, test, metrics